# Generated by Django 4.2.6 on 2024-03-27 18:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Avatar',
                'verbose_name_plural': 'Avatars',
            },
        ),
        migrations.RenameField(
            model_name='nnauser',
            old_name='is_tutor',
            new_name='is_autonomy_tutor',
        ),
        migrations.RemoveField(
            model_name='nnauser',
            name='autonomy_level',
        ),
        migrations.RemoveField(
            model_name='nnauser',
            name='mentors',
        ),
        migrations.RemoveField(
            model_name='staffuser',
            name='is_admin',
        ),
        migrations.AddField(
            model_name='nnauser',
            name='autonomy_tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.nnauser'),
        ),
        migrations.AddField(
            model_name='nnauser',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nnauser',
            name='development_level',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='nnauser',
            name='educators',
            field=models.ManyToManyField(blank=True, related_name='educators', to='users.staffuser'),
        ),
        migrations.AddField(
            model_name='nnauser',
            name='main_educator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_educator', to='users.staffuser'),
        ),
        migrations.AddField(
            model_name='nnauser',
            name='performance',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='nnauser',
            name='document',
            field=models.CharField(default='', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nnauser',
            name='entered_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nnauser',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Pending', 'Pending'), ('Frozen', 'Frozen'), ('Locked', 'Locked'), ('Suspended', 'Suspended')], default='Pending', max_length=255),
        ),
        migrations.AlterField(
            model_name='nnauser',
            name='therapist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='therapist', to='users.staffuser'),
        ),
        migrations.AddField(
            model_name='nnauser',
            name='avatar',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.avatar'),
        ),
    ]
