# Generated by Django 4.2.6 on 2023-10-28 17:30

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='document',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[users.validators.DocumentValidator()]),
        ),
    ]
