# Generated by Django 4.2.6 on 2024-02-14 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nnauser',
            name='is_tutor',
        ),
        migrations.AddField(
            model_name='nnauser',
            name='tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.nnauser'),
        ),
    ]
