# Generated by Django 4.2.8 on 2024-02-07 17:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import users.validators


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="date_of_birth",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="document",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="home",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="is_staff",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="roles",
        ),
        migrations.AddField(
            model_name="customuser",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="customuser",
            name="name",
            field=models.CharField(default="name", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="customuser",
            name="password",
            field=models.CharField(
                max_length=255, validators=[users.validators.PasswordValidator()]
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="surname",
            field=models.CharField(default="surname", max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="StaffUser",
            fields=[
                (
                    "customuser_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("is_admin", models.BooleanField(default=False)),
                ("homes", models.ManyToManyField(to="users.home")),
                ("roles", models.ManyToManyField(to="users.role")),
            ],
            options={
                "abstract": False,
            },
            bases=("users.customuser",),
        ),
        migrations.CreateModel(
            name="NNAUser",
            fields=[
                (
                    "customuser_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        validators=[users.validators.DocumentValidator()],
                    ),
                ),
                ("date_of_birth", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Pending", "Pending"),
                            ("Frozen", "Frozen"),
                            ("Locked", "Locked"),
                        ],
                        default="Pending",
                        max_length=255,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Other", "Other"),
                            ("Undefined", "Undefined"),
                        ],
                        default="Undefined",
                        max_length=255,
                    ),
                ),
                (
                    "autonomy_level",
                    models.IntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MaxValueValidator(10),
                            django.core.validators.MinValueValidator(1),
                        ],
                    ),
                ),
                ("is_tutor", models.BooleanField(default=False)),
                ("entered_at", models.DateField()),
                (
                    "home",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="users.home"
                    ),
                ),
                ("mentor", models.ManyToManyField(blank=True, to="users.staffuser")),
            ],
            options={
                "abstract": False,
            },
            bases=("users.customuser",),
        ),
    ]
