# Generated by Django 4.2.6 on 2023-10-23 15:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="therapist",
            name="customuser_ptr",
        ),
        migrations.RemoveField(
            model_name="therapist",
            name="location",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="polymorphic_ctype",
        ),
        migrations.DeleteModel(
            name="NNA",
        ),
        migrations.DeleteModel(
            name="Therapist",
        ),
    ]
