# Generated by Django 4.2.6 on 2023-11-07 16:50

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_customuser_document"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="status",
            field=models.CharField(
                choices=[
                    ("Active", "Active"),
                    ("Pending", "Pending"),
                    ("Frozen", "Frozen"),
                ],
                default="Pending",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="password",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                validators=[users.validators.PasswordValidator()],
            ),
        ),
    ]
