# Generated by Django 4.2.6 on 2024-03-27 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_avatar_rename_is_tutor_nnauser_is_autonomy_tutor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nnauser',
            name='document',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
