# Generated by Django 4.2.6 on 2024-02-15 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_nnauser_entered_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nnauser',
            name='document',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
