# Generated by Django 4.2.6 on 2023-10-23 15:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_customuser_options_customuser_date_of_birth_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="location",
            options={"ordering": ["id"]},
        ),
    ]
