# Generated by Django 4.2.8 on 2024-02-08 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_customuser_is_active"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="nnauser",
            options={"verbose_name": "NNA", "verbose_name_plural": "NNAs"},
        ),
        migrations.AlterModelOptions(
            name="staffuser",
            options={"verbose_name": "Staff", "verbose_name_plural": "Staff"},
        ),
        migrations.RemoveField(
            model_name="nnauser",
            name="mentor",
        ),
        migrations.AddField(
            model_name="nnauser",
            name="mentors",
            field=models.ManyToManyField(
                blank=True, related_name="mentors", to="users.staffuser"
            ),
        ),
        migrations.AddField(
            model_name="nnauser",
            name="therapist",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="users.staffuser",
            ),
        ),
    ]
