# Generated by Django 4.2.6 on 2024-02-22 11:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_nnauser_document'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nnauser',
            old_name='tutor',
            new_name='autonomy_tutor',
        ),
        migrations.RenameField(
            model_name='nnauser',
            old_name='mentors',
            new_name='educators',
        ),
        migrations.RemoveField(
            model_name='nnauser',
            name='autonomy_level',
        ),
        migrations.AddField(
            model_name='nnauser',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nnauser',
            name='development_level',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='nnauser',
            name='is_autonomy_tutor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nnauser',
            name='performance',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='nnauser',
            name='document',
            field=models.CharField(max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nnauser',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Pending', 'Pending'), ('Frozen', 'Frozen'), ('Locked', 'Locked'), ('Suspended', 'Suspended')], default='Pending', max_length=255),
        ),
    ]
