# Generated by Django 4.2.6 on 2024-02-22 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_tutor_nnauser_autonomy_tutor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nnauser',
            name='educators',
            field=models.ManyToManyField(blank=True, related_name='educators', to='users.staffuser'),
        ),
    ]
