# Generated by Django 4.2.6 on 2023-10-23 16:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_role_alter_location_options_customuser_roles"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Location",
            new_name="Home",
        ),
        migrations.RenameField(
            model_name="customuser",
            old_name="location",
            new_name="home",
        ),
    ]
