# Generated by Django 4.2.6 on 2023-10-12 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_therapist_student_mentor'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Active'), ('F', 'Frozen')], default='P', max_length=1),
        ),
    ]
