# Generated by Django 4.2.6 on 2024-02-29 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_avatar_nnauser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='nnauser',
            name='main_educator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_educator', to='users.staffuser'),
        ),
        migrations.AlterField(
            model_name='nnauser',
            name='therapist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='therapist', to='users.staffuser'),
        ),
    ]
