# Generated by Django 4.2.6 on 2023-10-13 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_student_status'),
    ]

    operations = [
        migrations.RenameModel('Student', 'NNA')
    ]
