# Generated by Django 4.2.10 on 2024-03-04 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_nnauser_main_educator_alter_nnauser_therapist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffuser',
            name='is_admin',
        ),
    ]
