# Generated by Django 4.2.8 on 2024-03-08 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_remove_staffuser_is_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="special_code",
            field=models.CharField(blank=True, default=""),
        ),
    ]
